# Generated by Django 4.1.6 on 2023-05-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='album',
        ),
        migrations.RemoveField(
            model_name='music',
            name='year',
        ),
    ]
